### ISSUE TITLE
Style.css not working

### ISSUE THREAD

**Issue by sayanp99** [sayanp99/Donate-TO-Happen#1]
the css is not working

**Comment by demonicirfan** [comment]
Hii can i work on this issue

**Comment by ORKO06** [comment]
I would like to work on this issue. Please assign it to me

**Comment by LaLiLuLeLoPS** [comment]
Hi i have extensive css knowledge, please assign this issue

**Comment by sayanp99** [comment]
Issue has been fixed and resolved #2
